import { PortfolioItem } from "@/types";

export const portfolioItems: PortfolioItem[] = [
  {
    id: "01",
    title: "A Armadilha Invisível do INSS",
    client: "Grid Marketing",
    category: "Reels & Direito",
    year: "2024",
    poster: "/imagens moldura/armadilha da invalidez.png",
    video: "https://youtube.com/shorts/YCsZNZ-m17E?feature=share",
    alt: "Moldura do vídeo A Armadilha Invisível do INSS",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "02",
    title: "O Segredo do Mármore Perfeito",
    client: "Grid Marketing",
    category: "Arquitetura & Design",
    year: "2024",
    poster: "/imagens moldura/bookmatching.png",
    video: "https://youtube.com/shorts/BJYz-7OKS-I?feature=share",
    alt: "Moldura do vídeo Bookmatching e Mármore",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "03",
    title: "A Maior Mentira do Audiovisual",
    client: "Grid Marketing",
    category: "Criativo & Direção",
    year: "2024",
    poster: "/imagens moldura/mentira.png",
    video: "https://youtube.com/shorts/aCcJi6VEYVg?feature=share",
    alt: "Moldura do vídeo A Maior Mentira do Audiovisual",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "04",
    title: "O Poder de Ressignificar sua Marca",
    client: "Grid Marketing",
    category: "Motion FX",
    year: "2024",
    poster: "/imagens moldura/resSIGNfique.png",
    video: "https://youtube.com/shorts/j-Dra0x2HM0?feature=share",
    alt: "Moldura do vídeo resSIGNfique",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "05",
    title: "Você Realmente Vai se Aposentar?",
    client: "Grid Marketing",
    category: "Edição Dinâmica",
    year: "2024",
    poster: "/imagens moldura/vai aposentar.png",
    video: "https://youtube.com/shorts/C8wza9OyzsM?feature=share",
    alt: "Moldura do vídeo Você Realmente Vai se Aposentar?",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "06",
    title: "Pasta Nono: O Erro de 240p",
    client: "Grid Marketing",
    category: "Marketing & Reels",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/240p.png",
    video: "https://youtube.com/shorts/z6u7w6p5ZKg?feature=share",
    alt: "Moldura do vídeo Pasta Nono 240p",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "07",
    title: "Como Salvar uma Venda Impossível",
    client: "Grid Marketing",
    category: "Atendimento & Vendas",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/agente resolveu atender.png",
    video: "https://youtube.com/shorts/nqn0XhDeKek?feature=share",
    alt: "Moldura do vídeo Pedraria Ivoti",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "08",
    title: "A História que Emociona e Converte",
    client: "Grid Marketing",
    category: "Storytelling",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/cafe dos pais.png",
    video: "https://youtube.com/shorts/5eCezWfRr9A?feature=share",
    alt: "Moldura do vídeo Café dos Pais",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "09",
    title: "Resolvendo o Caos da Entrega",
    client: "Grid Marketing",
    category: "Experiência do Cliente",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/eu lembro quando entreguei essa peça.png",
    video: "https://youtube.com/shorts/R0fI6beL7ss?feature=share",
    alt: "Moldura do vídeo Resolvendo Problema",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "10",
    title: "Cuidado: O INSS Pode Não Te Pagar",
    client: "Grid Marketing",
    category: "Direito Previdenciário",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/o inss nao vai te pagar.png",
    video: "https://youtube.com/shorts/b7tUBcHWBAY?feature=share",
    alt: "Moldura do vídeo Alerta INSS",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "11",
    title: "O Detalhe que Quase Ninguém Revisa",
    client: "Grid Marketing",
    category: "Revisão & Qualidade",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/posso revisar .png",
    video: "https://youtube.com/shorts/wnJQJsl8quU?feature=share",
    alt: "Moldura do vídeo Posso revisar?",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "12",
    title: "Qual Decisão Muda o Seu Jogo?",
    client: "Grid Marketing",
    category: "Engajamento",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/qual sua escolha.png",
    video: "https://youtube.com/shorts/6Mevt6cfDrQ?feature=share",
    alt: "Moldura do vídeo Qual sua escolha?",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "13",
    title: "O Método que 99% das Marcas Ignoram",
    client: "Grid Marketing",
    category: "Dicas & Estratégia",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/tem uma coisa que quase ninguem faz.png",
    video: "https://youtube.com/shorts/7tBGYfrJe18?feature=share",
    alt: "Moldura do vídeo Tem uma coisa que quase ninguém faz",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "14",
    title: "Por Trás da Ilusão de 'Só Instalar'",
    client: "Grid Marketing",
    category: "Marmoraria & Técnica",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/voce acha que e so cortar e instalar.png",
    video: "https://youtube.com/shorts/kgbxjqmRKM4?feature=share",
    alt: "Moldura do vídeo Você acha que é só cortar e instalar?",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "15",
    title: "Como Escolher a Pedra Perfeita na Loja",
    client: "Grid Marketing",
    category: "Guia de Compras",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/voce pode escolher uma pedra na loja.png",
    video: "https://youtube.com/shorts/fA4vHc3UVvA?feature=share",
    alt: "Moldura do vídeo Escolha de Pedra na Loja",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "16",
    title: "A Revolução Invisível: Nomad Chip",
    client: "Grid Marketing",
    category: "Tech & Lifestyle",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/Nomad eCHIP.png",
    video: "https://youtube.com/shorts/U8dBsqud1uY?feature=share",
    alt: "Moldura do vídeo Nomad Chip",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "17",
    title: "O Futuro nos Olhos: Ray-Ban Meta",
    client: "Grid Marketing",
    category: "Produto & Inovação",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/Rayban Meta.png",
    video: "https://youtube.com/shorts/ibrldvDBNyg?feature=share",
    alt: "Moldura do vídeo Ray-Ban Meta",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "18",
    title: "Do Caos Bruto à Obra-Prima",
    client: "Grid Marketing",
    category: "Bastidores & Processo",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/do bruto ao projeto.png",
    video: "https://youtube.com/shorts/3Mzjrb7DbNE?feature=share",
    alt: "Moldura do vídeo Do Bruto ao Projeto",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "19",
    title: "O Anúncio Criado para Escalar Vendas",
    client: "Grid Marketing",
    category: "Growth & Conversão",
    year: "2024",
    poster: "/imagens moldura/novos videos/molduras/GRID ANUNCIO.png",
    video: "https://youtube.com/shorts/tkXd3vp7mwc?feature=share",
    alt: "Moldura do vídeo Grid Anúncio",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "20",
    title: "Ritmo e Hipnose Visual: Escadaria",
    client: "Grid Marketing",
    category: "Motion & Edição",
    year: "2024",
    poster: "/imagens moldura/escadaria.png",
    video: "https://youtube.com/shorts/mZo0ZE9aKZY?feature=share",
    alt: "Moldura do vídeo Escadaria",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "21",
    title: "Destrave Sua Voz Antes que Seja Tarde",
    client: "Grid Marketing",
    category: "Reels & Comunicação",
    year: "2024",
    poster: "/imagens moldura/novos videos/molduras/TRAVA QUANDO PRECISA SER OUVIDO.png",
    video: "https://youtube.com/shorts/fARTyQcf-bg?feature=share",
    alt: "Moldura do vídeo Trava quando precisa ser ouvido",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "22",
    title: "Quanto Realmente Vale a Sua Ideia?",
    client: "Grid Marketing",
    category: "Posicionamento & Valor",
    year: "2024",
    poster: "/imagens moldura/novos videos/molduras/O VALOR DA SUA IDEIA.png",
    video: "https://youtube.com/shorts/SCYm4dEdeRQ?feature=share",
    alt: "Moldura do vídeo O valor da sua ideia",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "23",
    title: "O Ponto Cego Onde Você Perde Clientes",
    client: "Grid Marketing",
    category: "Estratégia & Retenção",
    year: "2024",
    poster: "/imagens moldura/novos videos/molduras/ONDE SUA COMUNICAÇAO PERDE FORÇA.png",
    video: "https://youtube.com/shorts/nl_G7Ta7Zp8?feature=share",
    alt: "Moldura do vídeo Onde sua comunicação perde força",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "24",
    title: "3 Erros que Destroem Ideias Brilhantes",
    client: "Grid Marketing",
    category: "Reels & Copywriting",
    year: "2024",
    poster: "/imagens moldura/novos videos/molduras/ENFRAQUECER SUA IDEIA.png",
    video: "https://youtube.com/shorts/O5vPWoy54Xk?feature=share",
    alt: "Moldura do vídeo Enfraquecer sua ideia",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "25",
    title: "A Estrutura de 3 Partes que Prende o Olhar",
    client: "Grid Marketing",
    category: "Narrativa & Retenção",
    year: "2024",
    poster: "/imagens moldura/novos videos/molduras/EM TRES PARTES.png",
    video: "https://youtube.com/shorts/EQNnxjD9py4?feature=share",
    alt: "Moldura do vídeo Em três partes",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "26",
    title: "O Teste de Sobrevivência na Ilha",
    client: "Grid Marketing",
    category: "Storytelling & Dinâmica",
    year: "2024",
    poster: "/imagens moldura/novos videos/molduras/DESAFIO DA ILHA.png",
    video: "https://youtube.com/shorts/NmHpAqU89kU?feature=share",
    alt: "Moldura do vídeo Desafio da Ilha",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "27",
    title: "De 240p ao Luxo: O Poder da Edição",
    client: "Grid Marketing",
    category: "Transformação Visual",
    year: "2024",
    poster: "/imagens moldura/novos videos/molduras/PEDRARIA 240P.png",
    video: "https://youtube.com/shorts/wRHiaDc14rg?feature=share",
    alt: "Moldura do vídeo Pedraria 240p",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "28",
    title: "O Benefício do INSS que Você Não Sabe",
    client: "Grid Marketing",
    category: "Direito & Reels",
    year: "2024",
    poster: "/imagens moldura/novos videos/molduras/não tem nenhum benefício do INSS.png",
    video: "https://youtube.com/shorts/HvRdE5ebRd4?feature=share",
    alt: "Moldura do vídeo Benefício do INSS",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
];
