import { PortfolioItem } from "@/types";

export const portfolioItems: PortfolioItem[] = [
  {
    id: "01",
    title: "Armadilha da Invalidez",
    client: "Grid Marketing",
    category: "Reels & Direito",
    year: "2024",
    poster: "/imagens moldura/armadilha da invalidez.png",
    video: "https://youtube.com/shorts/YCsZNZ-m17E?feature=share",
    alt: "Moldura 4:5 do vídeo Armadilha da Invalidez",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "02",
    title: "Bookmatching",
    client: "Grid Marketing",
    category: "Arquitetura & Design",
    year: "2024",
    poster: "/imagens moldura/bookmatching.png",
    video: "https://youtube.com/shorts/BJYz-7OKS-I?feature=share",
    alt: "Moldura 4:5 do vídeo Bookmatching",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "03",
    title: "Mentira",
    client: "Grid Marketing",
    category: "Criativo & Direção",
    year: "2024",
    poster: "/imagens moldura/mentira.png",
    video: "https://youtube.com/shorts/aCcJi6VEYVg?feature=share",
    alt: "Moldura 4:5 do vídeo Mentira",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "04",
    title: "resSIGNfique",
    client: "Grid Marketing",
    category: "Motion FX",
    year: "2024",
    poster: "/imagens moldura/resSIGNfique.png",
    video: "https://youtube.com/shorts/j-Dra0x2HM0?feature=share",
    alt: "Moldura 4:5 do vídeo resSIGNfique",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "05",
    title: "Vai Aposentar",
    client: "Grid Marketing",
    category: "Edição Dinâmica",
    year: "2024",
    poster: "/imagens moldura/vai aposentar.png",
    video: "https://youtube.com/shorts/C8wza9OyzsM?feature=share",
    alt: "Moldura 4:5 do vídeo Vai Aposentar",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "06",
    title: "Resolução 240p",
    client: "Grid Marketing",
    category: "Marketing & Reels",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/240p.png",
    video: "https://youtube.com/shorts/C3sORKLqTYo?feature=share",
    alt: "Moldura 4:5 do vídeo 240p",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "07",
    title: "Pedraria Ivoti",
    client: "Grid Marketing",
    category: "Atendimento & Vendas",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/agente resolveu atender.png",
    video: "https://youtube.com/shorts/JwjK67R-Ms4?feature=share",
    alt: "Moldura 4:5 do vídeo Pedraria Ivoti",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "08",
    title: "Café dos Pais",
    client: "Grid Marketing",
    category: "Storytelling",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/cafe dos pais.png",
    video: "/videos portfolio/Nova pasta/cafe dos pais.mp4",
    alt: "Moldura 4:5 do vídeo Café dos Pais",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "09",
    title: "Entrega da Peça",
    client: "Grid Marketing",
    category: "Experiência do Cliente",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/eu lembro quando entreguei essa peça.png",
    video: "/videos portfolio/Nova pasta/eu lembro quando entreguei essa peça.mp4",
    alt: "Moldura 4:5 do vídeo Eu lembro quando entreguei essa peça",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "10",
    title: "Alerta INSS",
    client: "Grid Marketing",
    category: "Direito Previdenciário",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/o inss nao vai te pagar.png",
    video: "/videos portfolio/Nova pasta/o inss nao vai te pagar.mp4",
    alt: "Moldura 4:5 do vídeo O INSS não vai te pagar",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "11",
    title: "Posso Revisar?",
    client: "Grid Marketing",
    category: "Revisão & Qualidade",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/posso revisar .png",
    video: "/videos portfolio/Nova pasta/posso revisar .mp4",
    alt: "Moldura 4:5 do vídeo Posso revisar",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "12",
    title: "Qual Sua Escolha?",
    client: "Grid Marketing",
    category: "Engajamento",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/qual sua escolha.png",
    video: "/videos portfolio/Nova pasta/qual sua escolha.mp4",
    alt: "Moldura 4:5 do vídeo Qual sua escolha",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "13",
    title: "Quase Ninguém Faz",
    client: "Grid Marketing",
    category: "Dicas & Estratégia",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/tem uma coisa que quase ninguem faz.png",
    video: "/videos portfolio/Nova pasta/tem uma coisa que quase ninguem faz.mp4",
    alt: "Moldura 4:5 do vídeo Tem uma coisa que quase ninguém faz",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "14",
    title: "É Só Cortar e Instalar?",
    client: "Grid Marketing",
    category: "Marmoraria & Técnica",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/voce acha que e so cortar e instalar.png",
    video: "/videos portfolio/Nova pasta/voce acha que e so cortar e instalar.mp4",
    alt: "Moldura 4:5 do vídeo Você acha que é só cortar e instalar",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "15",
    title: "Pedra na Loja",
    client: "Grid Marketing",
    category: "Guia de Compras",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/voce pode escolher uma pedra na loja.png",
    video: "/videos portfolio/Nova pasta/voce pode escolher uma pedra na loja.mp4",
    alt: "Moldura 4:5 do vídeo Você pode escolher uma pedra na loja",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "16",
    title: "Reel de Impacto",
    client: "Grid Marketing",
    category: "Produção Visual",
    year: "2024",
    poster: "/imagens moldura/Nova pasta/imrheaaa.png",
    video: "/videos portfolio/Nova pasta/imrheaaa_pindown.io_1786230189.mp4",
    alt: "Moldura 4:5 do vídeo Reel de Impacto",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "17",
    title: "Escadaria",
    client: "Grid Marketing",
    category: "Motion & Edição",
    year: "2024",
    poster: "/imagens moldura/escadaria.png",
    video: "https://youtube.com/shorts/mZo0ZE9aKZY?feature=share",
    alt: "Moldura 4:5 do vídeo Escadaria",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "18",
    title: "Trava quando precisa ser ouvido",
    client: "Grid Marketing",
    category: "Reels & Edição",
    year: "2024",
    poster: "/imagens moldura/novos videos/molduras/TRAVA QUANDO PRECISA SER OUVIDO.png",
    video: "/videos portfolio/videos novos/bespeak reels 1  versao 2 ajustada.mp4",
    alt: "Moldura 4:5 do vídeo Trava quando precisa ser ouvido",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "19",
    title: "O valor da sua ideia",
    client: "Grid Marketing",
    category: "Reels & Edição",
    year: "2024",
    poster: "/imagens moldura/novos videos/molduras/O VALOR DA SUA IDEIA.png",
    video: "/videos portfolio/videos novos/BESPEAK REELS 2 Versao 1.mp4",
    alt: "Moldura 4:5 do vídeo O valor da sua ideia",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "20",
    title: "Onde a sua comunicação perde força?",
    client: "Grid Marketing",
    category: "Reels & Edição",
    year: "2024",
    poster: "/imagens moldura/novos videos/molduras/ONDE SUA COMUNICAÇAO PERDE FORÇA.png",
    video: "/videos portfolio/videos novos/bespeak reels 3 versao 1.mp4",
    alt: "Moldura 4:5 do vídeo Onde a sua comunicação perde força?",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "21",
    title: "Enfraquecer a sua ideia",
    client: "Grid Marketing",
    category: "Reels & Edição",
    year: "2024",
    poster: "/imagens moldura/novos videos/molduras/ENFRAQUECER SUA IDEIA.png",
    video: "/videos portfolio/videos novos/bespeak reels 4 VERSAO 1.mp4",
    alt: "Moldura 4:5 do vídeo Enfraquecer a sua ideia",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "22",
    title: "Em três partes",
    client: "Grid Marketing",
    category: "Reels & Edição",
    year: "2024",
    poster: "/imagens moldura/novos videos/molduras/EM TRES PARTES.png",
    video: "/videos portfolio/videos novos/bespeak reels 5 VERSAO 1.mp4",
    alt: "Moldura 4:5 do vídeo Em três partes",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "23",
    title: "Desafio da Ilha",
    client: "Grid Marketing",
    category: "Storytelling & Dinâmica",
    year: "2024",
    poster: "/imagens moldura/novos videos/molduras/DESAFIO DA ILHA.png",
    video: "/videos portfolio/videos novos/desafio da ilha Versao 3.mp4",
    alt: "Moldura 4:5 do vídeo Desafio da Ilha",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "24",
    title: "Pedraria 240p",
    client: "Grid Marketing",
    category: "Criativo & Reels",
    year: "2024",
    poster: "/imagens moldura/novos videos/molduras/PEDRARIA 240P.png",
    video: "/videos portfolio/videos novos/pedraria 240p versao modificada.mp4",
    alt: "Moldura 4:5 do vídeo Pedraria 240p",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
  {
    id: "25",
    title: "Não tem nenhum benefício do INSS",
    client: "Grid Marketing",
    category: "Direito & Reels",
    year: "2024",
    poster: "/imagens moldura/novos videos/molduras/não tem nenhum benefício do INSS.png",
    video: "/videos portfolio/videos novos/REELS 1 voltou a trabalhar VERSAO 1.mp4",
    alt: "Moldura 4:5 do vídeo Não tem nenhum benefício do INSS",
    thumbnailAspectRatio: "4 / 5",
    videoAspectRatio: "9 / 16",
  },
];
